// export default {
//     id: 0,
//     created_at: '',
//     title: '',
//     office: '',
//     assign: '',
//     number: '',
//     supplier_id: '',
//     store_code: '',
//     last_exist : 0,
//     last_date : '',
//     last_numb : '',
//     customer_name : '',
//     curator : '',
// }
export default {
    id: 0,
    created_at: '2020-07-12',
    title: 'This is title',
    office: 'This is office',
    assign: 'Mr Assign',
    number: '3AR-TB',
    supplier_id: '3',
    store_code: '21BB-09',
    last_exist : 0,
    last_date : '',
    last_numb : '',
    customer_name : 'Mr Tong Teng',
    curator : 'Mrs Tester',
}